"""update

Revision ID: 4fdc730e881d
Revises: c0deb33c17f3
Create Date: 2022-12-08 09:05:50.119002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdc730e881d'
down_revision = 'c0deb33c17f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
