"""update

Revision ID: c0deb33c17f3
Revises: 670f4caac7dd
Create Date: 2022-12-08 09:04:58.053709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0deb33c17f3'
down_revision = '670f4caac7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('items', sa.ARRAY(sa.PickleType()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'items')
    # ### end Alembic commands ###
